### ISSUE TITLE
list of features hardcoded into plotting Javascript

### ISSUE THREAD

**Issue by joefutrelle** [joefutrelle/oii#50]
Introduced in 2f572943

There's a FIXME-style comment in the code pointing this out:

>  Hard coded simply because I don't know / want to find out how to pull this from Python where the csv is read. This is easier

could cause issues when plotting datasets with different sets of features.

**Comment by joefutrelle** [comment]
Wait a second. Using feature columns isn't working because this graphing capability is not supposed to plot features, it's supposed to plot ADC data. It needs to know the ADC columns, not the columns in feature files, and this definitely requires a different set for old-style IFCB data and for new-style IFCB data.

**Comment by joefutrelle** [comment]
I see, the implementation serves four ADC columns (bottom, left, fluorescenceLow, scatteringLow) and then if there is a features file, serves all the features (but not the features schema).

This causes a variety of problems. First, there are no columns called fluorescenceLow and scatteringLow in new-style ADC data. Second, the features schema may change over time (that's the issue with having them hardcoded). So this whole capability needs to be made more schema-aware both on the client and server side.

**Comment by hsosik** [comment]
Lou asked me specifically about this and I agreed to the hard coding of the feature list just for the pull down so it doesn't have to be parsed over and over from individual feature files - I gather you have a different system for tracking the schema? My understanding is that the handling of the ADC schema is not changed from the original EXCEPT that for hard coding of old style fluorescenceLow, scatteringLow now being multiplied by -1 before plotting - that doesn't apply to new style so hard coding could be OK?

**Comment by joefutrelle** [comment]
I understand now what the desired capability is: you want to be able to plot all the ADC columns *and* all the feature columns.

My old Javascript code also had old-style fluorescence / scattering columns hardcoded into it, so this problem was not introduced in the new code.

We can avoid the hardcoding of the feature schema and finesse the issue of reading lots of feature files by making the assumption that the feature schema is constant per-time-series. Then I can "memoize" [sic] the feature schema the first time it's requested for a given time series, and then no more feature files need to be read.

We can proceed with testing before I make these fixes.

**Comment by hsosik** [comment]
One thing I am just catching up to now is that apparently fluorescence vs scattering plots never worked on new style data...

**Comment by LouisK130** [comment]
Since we'll have to read the feature file every time somebody requests a plot using a property from the feature file anyways, we could just return the schema along with the point data that's requested from <code>/<time_series>/api/plot/<path:params>/pid/<url:pid><code>.

If we use this to populate the drop down menus, then the feature file would have to be read with any plotting request, regardless of whether or not a feature property was being requested. Not too much extra overhead, but is this better/easier than "memozing" [sic]?

**Comment by joefutrelle** [comment]
I was operating under the--I think incorrect--assumption that the drop-down menu needs to be populated in the GUI before the plot data is delivered to the client. But a plot is drawn immediately when the interface is drawn, so it could all be delivered at once.

But I already have the memoized endpoint implemented, and it's a bit cleaner way of accomplishing this because it only ever has to read a feature file once per time series, and it's not conditional on which variables the user has selected in the plot.

The default behavior is to plot ADC columns rather than features, and so if delivering the feature schema to the client was conditional on which columns were selected to plot, the dropdowns wouldn't initially get populated with feature columns, and then there would be no way of selecting them.
