### ISSUE TITLE
Log plotting of fluorescence / scattering produces blank graph

### ISSUE THREAD

**Issue by joefutrelle** [joefutrelle/oii#51]
Possible issue introduced in 2f57294

I'm getting a blank graph when I try to log plot fluorescenceLow vs. scatteringLow.

**Comment by LouisK130** [comment]
If some values are negative, an offset is required to make sure all are positive before plotting with log.

**Comment by joefutrelle** [comment]
You mean the user has to enter the offset in the box in the interface?

**Comment by LouisK130** [comment]
Yes, that's why my mom wanted the offset options.

**Comment by joefutrelle** [comment]
Works as advertised.
